
name: lint

on:
  pull_request:
    branches: [onekey]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-
      - name: Install Dependiences
        run: yarn install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Log Info
        run: |
          echo "node version: $(node -v)"
          echo "npm version: $(npm -v)"
          echo "webpack version: $(./node_modules/.bin/webpack -v)"
      - name: Lint & Type Check
        run: |
          yarn lint
          yarn test:unit
