name: package-publish

on: workflow_dispatch

jobs:
  package-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install Package
        run: |
          yarn
      - name: Build Target
        run: |
          yarn build
          yarn build:npm
          yarn build:npm-extended
      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd npm && yarn publish && cd ..
          cd npm-extended && yarn publish && cd ..